### ISSUE TITLE
About the reached maximum throughput of Orca?

### ISSUE THREAD

**Issue by wen-zheng** [Soheil-ab/Orca#2] opened 2020-09-05 09:10 UTC
@Soheil-ab 

Hi, Soheil.
I set the following network topology:

client ---------- router------------- server

and set the bottleneck bandwidth with 128Mbps, RTT with 150ms, and queue length with 1BDP at the router using Linux tc and netem.
I found the maximum throughput of Orca is only ~60Mbps but pure cubic can reach 100+Mbps?
Do I need to configure Orca specifically for this environment? (I have asked you how to run Orca without mahimahi.)

**Comment by wen-zheng** [comment] 2020-09-05 09:16
My configurations:
OS: ubuntu 16.04
CPU: 1
Ram: 1GB
tcp_timestamps: disabled
tcp offload: disabled
net.core.rmem_max: 33554432
net.core.wmem_max: 33554432
net.core.rmem_default: 16777216
net.core.wmem_default:16777216
net.ipv4.tcp_wmem: '8388608 16777216 33554432'
sysctl net.ipv4.tcp_rmem: '8388608 16777216 33554432'
and I have comment the settings for wmem at setup.sh script.

Orca's overhead: ~5% CPU

**Comment by Soheil-ab** [comment] 2020-09-06 07:12
@wen-zheng ,

Hi Wen-Zheng, it sounds like a problem with reading the correct learned model. Make sure that the provided model is not replaced with a new model. That can happen if you accidentally started a "learn from scratch" session. To see if everything is alright at the server side, first, use Mahimahi and create a bottleneck link similar to your topology. Then send traffic to see if the problem persists. If it does, then problem is with the model you're using, if not, we will look into other possible reasons.

Plz let me know the outcome.

(Just as a side note: Plz set followings:
sudo sysctl -q net.ipv4.tcp_wmem="4096 32768 4194304"
sudo sysctl -w -q net.ipv4.tcp_low_latency=1
sudo sysctl -w -q net.ipv4.tcp_autocorking=0
sudo sysctl -w -q net.ipv4.tcp_no_metrics_save=1
)

**Comment by wen-zheng** [comment] 2020-09-07 03:21
@Soheil-ab 

I have checked the md5 of the trained model at folder "models" and "rl-module/train_dir/learner0" which is the same with this repository.

And I restore the default settings (net.ipv4.tcp_wmem="4096 32768 4194304") but this issue remains.

I also found that the results of repeated experiments in the same environment (bottleneck bandwidth and RTT are fixed) can vary greatly.

**Comment by Soheil-ab** [comment] 2020-09-07 08:52
@wen-zheng ,

OK. Now let's check other things. 

Are you using VMs (on top of VMWare, VBox, ... )? Current implementation is not fully in-kernel meaning part of the system is still at app layer. In particular, information passing b.w. kernel, "c",  and "python" is handled by timers at app layer. Consequently, if you are using a VM with very restricted resources (similar to your case), you will see that performance drops, because your host OS will schedule the VM tightly and that impacts the performance of the timers therein which will lead to results vary a lot even on the same setting. Besides, current implementation still uses Tensorflow which requires enough resources to perform its job smoothly.

So, if you can, avoid using VMs (Type 2 Hypervisors). Instead, for instance, use bare-metal Hypervisors if you can. If it's not the case, try to increase the resources (Specifically CPU and RAM) associated to the VM and see the impact on the results. In general, a low performing VM will greatly impact the performance including performance of TCP schemes (even the fully in-kernel ones like Cubic or BBR).

Plz let me know if it resolves the issue.

**Comment by wen-zheng** [comment] 2020-09-07 12:40
@Soheil-ab 

I do use VMs. And I allocate more resources to Orca's server and client (4 CPU, 2G RAM), but the above issues remain. I also test Cubic, BBR between Orca's server, client and their performance is very consistent.

My experiment results are as below (15 Mbps, 150 ms RTT, Tcptrace's stats):

Orca 1st test: 

1 arg remaining, starting with '/tmp/comparing.pcap'
Ostermann's tcptrace -- version 6.6.7 -- Thu Nov  4, 2004

8553 packets seen, 8258 TCP packets traced, 0 UDP packets traced
elapsed wallclock time: 0:00:00.013326, 641828 pkts/sec analyzed
trace file elapsed time: 0:00:29.700928
TCP connection info:
1 TCP connection traced:
TCP connection 1:
        host a:        192.168.240.133:57396
        host b:        192.168.72.137:50001
        complete conn: no        (SYNs: 2)  (FINs: 0)
        first packet:  Mon Sep  7 13:18:54.317738 2020
        last packet:   Mon Sep  7 13:19:24.016830 2020
        elapsed time:  0:00:29.699092
        total packets: 8258
        filename:      /tmp/comparing.pcap
   a->b:                              b->a:
     total packets:          4115           total packets:          4143      
     ack pkts sent:          4114           ack pkts sent:          4143      
     pure acks sent:         4113           pure acks sent:            1      
     sack pkts sent:         3748           sack pkts sent:            0      
     dsack pkts sent:           0           dsack pkts sent:           0      
     max sack blks/ack:         4           max sack blks/ack:         0      
     unique bytes sent:        44           unique bytes sent:  12043700      
     actual data pkts:          1           actual data pkts:       4141      
     actual data bytes:        44           actual data bytes:  12043700      
     rexmt data pkts:           0           rexmt data pkts:           0      
     rexmt data bytes:          0           rexmt data bytes:          0      
     zwnd probe pkts:           0           zwnd probe pkts:           0      
     zwnd probe bytes:          0           zwnd probe bytes:          0      
     outoforder pkts:           0           outoforder pkts:        2762      
     pushed data pkts:          1           pushed data pkts:        171      
     SYN/FIN pkts sent:       1/0           SYN/FIN pkts sent:       1/0      
     req 1323 ws/ts:          Y/N           req 1323 ws/ts:          Y/N      
     adv wind scale:           10           adv wind scale:           10      
     req sack:                  Y           req sack:                  Y      
     sacks sent:             3748           sacks sent:                0      
     urgent data pkts:          0 pkts      urgent data pkts:          0 pkts 
     urgent data bytes:         0 bytes     urgent data bytes:         0 bytes
     mss requested:          1460 bytes     mss requested:          1460 bytes
     max segm size:            44 bytes     max segm size:         64240 bytes
     min segm size:            44 bytes     min segm size:           392 bytes
     avg segm size:            43 bytes     avg segm size:          2908 bytes
     max win adv:         8387584 bytes     max win adv:           29696 bytes
     min win adv:           29696 bytes     min win adv:           29696 bytes
     zero win adv:              0 times     zero win adv:              0 times
     avg win adv:         7277542 bytes     avg win adv:           29696 bytes
     initial window:           44 bytes     initial window:         8192 bytes
     initial window:            1 pkts      initial window:            1 pkts 
     ttl stream length:        NA           ttl stream length:        NA      
     missed data:              NA           missed data:              NA      
     truncated data:            0 bytes     truncated data:     11853214 bytes
     truncated packets:         0 pkts      truncated packets:      4141 pkts 
     data xmit time:        0.000 secs      data xmit time:       29.395 secs 
     idletime max:          151.8 ms        idletime max:          151.8 ms   
     throughput:                1 Bps       throughput:           405524 Bps  
no traced UDP packets

Orca 2nd test: 
1 arg remaining, starting with '/tmp/comparing.pcap'
Ostermann's tcptrace -- version 6.6.7 -- Thu Nov  4, 2004

42767 packets seen, 42468 TCP packets traced, 0 UDP packets traced
elapsed wallclock time: 0:00:00.035514, 1204229 pkts/sec analyzed
trace file elapsed time: 0:00:29.968838
TCP connection info:
1 TCP connection traced:
TCP connection 1:
        host a:        192.168.240.133:42664
        host b:        192.168.72.137:50002
        complete conn: no        (SYNs: 2)  (FINs: 0)
        first packet:  Mon Sep  7 13:19:46.565083 2020
        last packet:   Mon Sep  7 13:20:16.531992 2020
        elapsed time:  0:00:29.966909
        total packets: 42468
        filename:      /tmp/comparing.pcap
   a->b:                              b->a:
     total packets:         21203           total packets:         21265      
     ack pkts sent:         21202           ack pkts sent:         21265      
     pure acks sent:        21201           pure acks sent:            1      
     sack pkts sent:        17733           sack pkts sent:            0      
     dsack pkts sent:           0           dsack pkts sent:           0      
     max sack blks/ack:         4           max sack blks/ack:         0      
     unique bytes sent:        44           unique bytes sent:  53058748      
     actual data pkts:          1           actual data pkts:      21263      
     actual data bytes:        44           actual data bytes:  53058748      
     rexmt data pkts:           0           rexmt data pkts:           0      
     rexmt data bytes:          0           rexmt data bytes:          0      
     zwnd probe pkts:           0           zwnd probe pkts:           0      
     zwnd probe bytes:          0           zwnd probe bytes:          0      
     outoforder pkts:           0           outoforder pkts:        9990      
     pushed data pkts:          1           pushed data pkts:        125      
     SYN/FIN pkts sent:       1/0           SYN/FIN pkts sent:       1/0      
     req 1323 ws/ts:          Y/N           req 1323 ws/ts:          Y/N      
     adv wind scale:           10           adv wind scale:           10      
     req sack:                  Y           req sack:                  Y      
     sacks sent:            17733           sacks sent:                0      
     urgent data pkts:          0 pkts      urgent data pkts:          0 pkts 
     urgent data bytes:         0 bytes     urgent data bytes:         0 bytes
     mss requested:          1460 bytes     mss requested:          1460 bytes
     max segm size:            44 bytes     max segm size:         48836 bytes
     min segm size:            44 bytes     min segm size:            44 bytes
     avg segm size:            43 bytes     avg segm size:          2495 bytes
     max win adv:         8636416 bytes     max win adv:           29696 bytes
     min win adv:           29696 bytes     min win adv:           29696 bytes
     zero win adv:              0 times     zero win adv:              0 times
     avg win adv:         8167560 bytes     avg win adv:           29696 bytes
     initial window:           44 bytes     initial window:         8192 bytes
     initial window:            1 pkts      initial window:            1 pkts 
     ttl stream length:        NA           ttl stream length:        NA      
     missed data:              NA           missed data:              NA      
     truncated data:            0 bytes     truncated data:     52080652 bytes
     truncated packets:         0 pkts      truncated packets:     21262 pkts 
     data xmit time:        0.000 secs      data xmit time:       29.664 secs 
     idletime max:          151.6 ms        idletime max:          151.3 ms   
     throughput:                1 Bps       throughput:          1770578 Bps  
no traced UDP packets


cubic 1st test:

1 arg remaining, starting with '/tmp/comparing.pcap'
Ostermann's tcptrace -- version 6.6.7 -- Thu Nov  4, 2004

35574 packets seen, 35270 TCP packets traced, 4 UDP packets traced
elapsed wallclock time: 0:00:00.054803, 649125 pkts/sec analyzed
trace file elapsed time: 0:00:30.262700
TCP connection info:
1 TCP connection traced:
TCP connection 1:
        host a:        192.168.240.133:50000
        host b:        192.168.72.137:80
        complete conn: RESET        (SYNs: 2)  (FINs: 1)
        first packet:  Mon Sep  7 08:18:48.508496 2020
        last packet:   Mon Sep  7 08:19:18.769174 2020
        elapsed time:  0:00:30.260677
        total packets: 35270
        filename:      /tmp/comparing.pcap
   a->b:                              b->a:
     total packets:         17499           total packets:         17771      
     resets sent:             161           resets sent:               0      
     ack pkts sent:         17337           ack pkts sent:         17771      
     pure acks sent:        17335           pure acks sent:            1      
     sack pkts sent:         1736           sack pkts sent:            0      
     dsack pkts sent:           0           dsack pkts sent:           0      
     max sack blks/ack:         4           max sack blks/ack:         0      
     unique bytes sent:        86           unique bytes sent:  53503160      
     actual data pkts:          1           actual data pkts:      17769      
     actual data bytes:        86           actual data bytes:  53503160      
     rexmt data pkts:           0           rexmt data pkts:           0      
     rexmt data bytes:          0           rexmt data bytes:          0      
     zwnd probe pkts:           0           zwnd probe pkts:           0      
     zwnd probe bytes:          0           zwnd probe bytes:          0      
     outoforder pkts:           0           outoforder pkts:         190      
     pushed data pkts:          1           pushed data pkts:         44      
     SYN/FIN pkts sent:       1/1           SYN/FIN pkts sent:       1/0      
     req 1323 ws/ts:          Y/N           req 1323 ws/ts:          Y/N      
     adv wind scale:           10           adv wind scale:           10      
     req sack:                  Y           req sack:                  Y      
     sacks sent:             1736           sacks sent:                0      
     urgent data pkts:          0 pkts      urgent data pkts:          0 pkts 
     urgent data bytes:         0 bytes     urgent data bytes:         0 bytes
     mss requested:          1460 bytes     mss requested:          1460 bytes
     max segm size:            86 bytes     max segm size:         64240 bytes
     min segm size:            86 bytes     min segm size:          1460 bytes
     avg segm size:            85 bytes     avg segm size:          3011 bytes
     max win adv:         8387584 bytes     max win adv:           29696 bytes
     min win adv:           29696 bytes     min win adv:           29696 bytes
     zero win adv:              0 times     zero win adv:              0 times
     avg win adv:         8173037 bytes     avg win adv:           29696 bytes
     initial window:           86 bytes     initial window:        14600 bytes
     initial window:            1 pkts      initial window:            1 pkts 
     ttl stream length:        86 bytes     ttl stream length:        NA      
     missed data:               0 bytes     missed data:              NA      
     truncated data:           40 bytes     truncated data:     52685786 bytes
     truncated packets:         1 pkts      truncated packets:     17769 pkts 
     data xmit time:        0.000 secs      data xmit time:       29.956 secs 
     idletime max:          153.4 ms        idletime max:          151.5 ms   
     throughput:                3 Bps       throughput:          1768075 Bps  

cubic 2nd test:
1 arg remaining, starting with '/tmp/comparing.pcap'
Ostermann's tcptrace -- version 6.6.7 -- Thu Nov  4, 2004

34058 packets seen, 33761 TCP packets traced, 0 UDP packets traced
elapsed wallclock time: 0:00:00.032757, 1039716 pkts/sec analyzed
trace file elapsed time: 0:00:29.836999
TCP connection info:
1 TCP connection traced:
TCP connection 1:
        host a:        192.168.240.133:50001
        host b:        192.168.72.137:80
        complete conn: no        (SYNs: 2)  (FINs: 0)
        first packet:  Mon Sep  7 08:19:39.228192 2020
        last packet:   Mon Sep  7 08:20:09.063265 2020
        elapsed time:  0:00:29.835073
        total packets: 33761
        filename:      /tmp/comparing.pcap
   a->b:                              b->a:
     total packets:         16758           total packets:         17003      
     ack pkts sent:         16757           ack pkts sent:         17003      
     pure acks sent:        16756           pure acks sent:            1      
     sack pkts sent:         1913           sack pkts sent:            0      
     dsack pkts sent:           0           dsack pkts sent:           0      
     max sack blks/ack:         4           max sack blks/ack:         0      
     unique bytes sent:        86           unique bytes sent:  51546760      
     actual data pkts:          1           actual data pkts:      17001      
     actual data bytes:        86           actual data bytes:  51546760      
     rexmt data pkts:           0           rexmt data pkts:           0      
     rexmt data bytes:          0           rexmt data bytes:          0      
     zwnd probe pkts:           0           zwnd probe pkts:           0      
     zwnd probe bytes:          0           zwnd probe bytes:          0      
     outoforder pkts:           0           outoforder pkts:         342      
     pushed data pkts:          1           pushed data pkts:         48      
     SYN/FIN pkts sent:       1/0           SYN/FIN pkts sent:       1/0      
     req 1323 ws/ts:          Y/N           req 1323 ws/ts:          Y/N      
     adv wind scale:           10           adv wind scale:           10      
     req sack:                  Y           req sack:                  Y      
     sacks sent:             1913           sacks sent:                0      
     urgent data pkts:          0 pkts      urgent data pkts:          0 pkts 
     urgent data bytes:         0 bytes     urgent data bytes:         0 bytes
     mss requested:          1460 bytes     mss requested:          1460 bytes
     max segm size:            86 bytes     max segm size:         64240 bytes
     min segm size:            86 bytes     min segm size:          1460 bytes
     avg segm size:            85 bytes     avg segm size:          3031 bytes
     max win adv:         8387584 bytes     max win adv:           29696 bytes
     min win adv:           29696 bytes     min win adv:           29696 bytes
     zero win adv:              0 times     zero win adv:              0 times
     avg win adv:         8269880 bytes     avg win adv:           29696 bytes
     initial window:           86 bytes     initial window:         5840 bytes
     initial window:            1 pkts      initial window:            1 pkts 
     ttl stream length:        NA           ttl stream length:        NA      
     missed data:              NA           missed data:              NA      
     truncated data:           40 bytes     truncated data:     50764714 bytes
     truncated packets:         1 pkts      truncated packets:     17001 pkts 
     data xmit time:        0.000 secs      data xmit time:       29.532 secs 
     idletime max:          152.0 ms        idletime max:          152.0 ms   
     throughput:                3 Bps       throughput:          1727724 Bps  
no traced UDP packets

**Comment by wen-zheng** [comment] 2020-09-07 12:55
Orca can perform good, but sometimes bad.

**Comment by Soheil-ab** [comment] 2020-09-12 04:58
@wen-zheng,

Unfortunately, summary of a pcap file won't help debugging the system. 

To see what is wrong, let's generate a reproducible scenario. To that end, please use Mahimahi, set the link BW to 12Mbps (a file with only a 1 on it can be used to generate a 12Mbps link in Mahimahi), RTT to 150ms, and queue size to 1BDP. Use your current setting and run a few tests with Orca over this environment and let me know the results.

**Comment by Soheil-ab** [comment] 2020-09-19 05:41
I close this issue due to lack of any activities.

**Closed by Soheil-ab** 2020-09-19 05:41 UTC
